// build-images.mjs
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { imageSize } from 'image-size'; // supports HEIC/AVIF [web:176][web:173]

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Adjust if your structure is different
const FULL_DIR = path.join(__dirname, 'images', 'full');
const THUMB_DIR = path.join(__dirname, 'images', 'thumbs');
const SCRIPT_PATH = path.join(__dirname, 'script.js');

// Read full-size AVIFs
const allEntries = fs.readdirSync(FULL_DIR, { withFileTypes: true });
const avifFiles = allEntries
  .filter((d) => d.isFile())
  .map((d) => d.name)
  .filter((name) => /\.avif$/i.test(name));

if (!avifFiles.length) {
  console.warn('No .avif files found in images/full/');
}

// Build imageFiles array
const imageFiles = [];

for (const name of avifFiles) {
  const fullPath = path.join(FULL_DIR, name);
  const thumbPath = path.join(THUMB_DIR, name); // same filename in thumbs/

  let width, height;
  try {
    const dims = imageSize(fullPath);
    width = dims.width;
    height = dims.height;
  } catch (err) {
    console.warn(`Could not read dimensions for ${name}:`, err.message);
  }

  const hasThumb = fs.existsSync(thumbPath);

  imageFiles.push({
    href: `images/full/${name}`,
    thumb: hasThumb ? `images/thumbs/${name}` : `images/full/${name}`,
    title: name.replace(/\.avif$/i, ''), // strip extension for nicer titles
    w: width || null,
    h: height || null
  });
}

// Generate script.js content

const header = `// script.js
// AUTO-GENERATED by build-images.mjs
// Do not edit the imageFiles array by hand; run \`node build-images.mjs\` after changing images.

const imageFiles = ${JSON.stringify(imageFiles, null, 2)};

`;

const body = `const linksContainer = document.getElementById('links');

console.log('linksContainer =', linksContainer);
console.log('imageFiles count =', imageFiles.length);

imageFiles.forEach((file, index) => {
  const a = document.createElement('a');
  a.href = file.href;
  a.dataset.index = index;
  if (file.title) a.title = file.title;

  const img = document.createElement('img');
  img.src = file.thumb || file.href;
  img.alt = file.title || \`Image \${index + 1}\`;

  a.appendChild(img);
  linksContainer.appendChild(a);
});
`;

// Write file
fs.writeFileSync(SCRIPT_PATH, header + body, 'utf8');

console.log(`Wrote ${imageFiles.length} items to script.js`);

fs.writeFileSync(SCRIPT_PATH, header + body, 'utf8');

console.log('Wrote', imageFiles.length, 'items to script.js');
console.log('SCRIPT_PATH =', SCRIPT_PATH);

