// script.js

// This array should be auto-generated by your build script:
// Each item is an object describing one media item.
const imageFiles = [
  // {
  //   href: "images/full/bee1.jpg",       // full-size image
  //   thumb: "images/thumbs/bee1.jpg",    // thumbnail
  //   title: "Worker bee on frame"        // optional
  // }
];

const linksContainer = document.getElementById('links');

imageFiles.forEach((file, index) => {
  const a = document.createElement('a');
  a.href = file.href;
  a.dataset.index = index;

  if (file.title) {
    a.title = file.title;
  }

  // Thumbnail image
  const img = document.createElement('img');
  img.src = file.thumb || file.href;
  img.alt = file.title || `Image ${index + 1}`;

  a.appendChild(img);
  linksContainer.appendChild(a);
});
