// script.js
// AUTO-GENERATED by build-images.mjs
// Do not edit the imageFiles array by hand; run `node build-images.mjs` after changing images.

const imageFiles = [
  {
    "href": "images/full/Beekeepers Mt Adams.avif",
    "thumb": "images/thumbs/Beekeepers Mt Adams.avif",
    "title": "Beekeepers Mt Adams",
    "w": null,
    "h": null
  },
  {
    "href": "images/full/Beekeepers Pouto Beach.avif",
    "thumb": "images/thumbs/Beekeepers Pouto Beach.avif",
    "title": "Beekeepers Pouto Beach",
    "w": null,
    "h": null
  },
  {
    "href": "images/full/Beekeepers Pouto Lake.avif",
    "thumb": "images/thumbs/Beekeepers Pouto Lake.avif",
    "title": "Beekeepers Pouto Lake",
    "w": null,
    "h": null
  },
  {
    "href": "images/full/Beekeepers Wairarapa.avif",
    "thumb": "images/thumbs/Beekeepers Wairarapa.avif",
    "title": "Beekeepers Wairarapa",
    "w": null,
    "h": null
  },
  {
    "href": "images/full/Homestead Bay RGB4.avif",
    "thumb": "images/thumbs/Homestead Bay RGB4.avif",
    "title": "Homestead Bay RGB4",
    "w": null,
    "h": null
  },
  {
    "href": "images/full/Manuka_Rimnunui_night_final.avif",
    "thumb": "images/thumbs/Manuka_Rimnunui_night_final.avif",
    "title": "Manuka_Rimnunui_night_final",
    "w": null,
    "h": null
  }
];

const linksContainer = document.getElementById('links');

console.log('linksContainer =', linksContainer);
console.log('imageFiles count =', imageFiles.length);

imageFiles.forEach((file, index) => {
  const a = document.createElement('a');
  a.href = file.href;
  a.dataset.index = index;
  if (file.title) a.title = file.title;

  const img = document.createElement('img');
  img.src = file.thumb || file.href;
  img.alt = file.title || `Image ${index + 1}`;

  a.appendChild(img);
  linksContainer.appendChild(a);
});
